---
- name: Install and configure Nginx
  hosts: m-web
  become: true

  vars:
    my_name: "Muhari Adrienn"

  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
        update_cache: true

    - name: Start and enable Nginx service
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started

    - name: Ensure /usr/share/nginx/html directory exists
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'

    - name: Deploy custom index.html from template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Restart Nginx to apply changes
      ansible.builtin.systemd:
        name: nginx
        state: restarted
